### ISSUE TITLE
test

### ISSUE THREAD

**Issue by v4lli** [v4lli/meteocool#1]

**Comment by Wheedman** [comment]
![Screenshot_20190510-140202_meteocool 2](https://user-images.githubusercontent.com/24626073/57528249-26eaec80-7332-11e9-97e5-92a94c34da50.jpg)
![Screenshot_20190509-232313_meteocool 1](https://user-images.githubusercontent.com/24626073/57528258-2d796400-7332-11e9-827f-4e836e474c91.jpg)
![Screenshot_20190509-232339_meteocool 1](https://user-images.githubusercontent.com/24626073/57528263-336f4500-7332-11e9-8fb9-1740387dd969.jpg)
![Screenshot_20190510-140218_meteocool 1](https://user-images.githubusercontent.com/24626073/57528282-3b2ee980-7332-11e9-820a-400c68822b44.jpg)

**Comment by v4lli** [comment]
![download-on-playstore](https://user-images.githubusercontent.com/1577223/57536457-84883480-7344-11e9-899d-c31ac124917c.png)
