### ISSUE TITLE
use geolocation from app in webview

### ISSUE THREAD

**Issue by v4lli** [v4lli/meteocool#115]
In the iOS app, the main webview needs to re-request permission for geolocation from the user every time the app is restarted after being force-quitted. This is really annoying, since the user already granted geolocation permission to the app, so we could just use that. Apparently it's a thing to do this by hooking some swift function from javascript in the place where the web app requests the navigator's geolocation feature. Alternatively we could just "inject" the location into the webapp using ``evaluateJavaScript(_:completionHandler:)
``. https://developer.apple.com/documentation/webkit/wkwebview/1415017-evaluatejavascript

**Comment by Flowm** [comment]
https://stackoverflow.com/questions/39665367/how-to-prevent-wkwebview-to-repeatedly-ask-for-permission-to-access-location/43907448#43907448

**Comment by v4lli** [comment]
@Flowm I think we have two options, either re-use the CLLocationManger from your LocationUpdater swift class or create a separate instance in ViewController.swift. Since the LocationUpdater instance is tied to AppDelegate AND it has a different accuracy requirement, I'd opt for the latter. Thoughts?
