### ISSUE TITLE
improve onboarding experience

### ISSUE THREAD

**Issue by Flowm** [v4lli/meteocool#117]
Explain the usage of Notifications and Location information to first time app users.

https://github.com/matteocrippa/awesome-swift/blob/master/README.md#walkthrough

**Comment by thomasgruebler** [comment]
Notification question popped up two times:
1. the app asks
2. "http://..." wants to use your location

**Comment by Flowm** [comment]
Thanks for the report.
This is caused by the apps webview not granting location access to all websites by default.

A potential fix is described in issue https://github.com/v4lli/meteocool/issues/115 and might be implemented in a future version.

**Comment by v4lli** [comment]
Resolved in iOS app v1.0.
