### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Nina2244** [v4lli/meteocool#135]
Apps/Website in other languages (german -> we only support germany).

**Comment by v4lli** [comment]
This is in progress now/almost done, fyi @dfsan

**Comment by v4lli** [comment]
Android localization still missing. @Wheedman can you provide the app language ("de" or "en") as the "lang" key in the /post_location JSON request? Push notifications will be translated automatically in the backend now.

**Comment by dfsan** [comment]
ok

**Comment by v4lli** [comment]
Done on iOS, issue created in meteocool/android for 2.0.
