### ISSUE TITLE
slow network connection testing

### ISSUE THREAD

**Issue by pew** [v4lli/meteocool#147]
when opening up meteocool on a slow network connection you either get:

* a blank white page
* the meteocool header and a blank page

when you click the button on the right, a spinner will become visible in a weird location. see screen shots (iphone se)

suggestion / idea: show some sort of loading spinner from the beginning, after a certain timeout (10s?) "warn" user about slow network?

![IMG_0043](https://user-images.githubusercontent.com/52463/56815857-9943d300-6842-11e9-83b5-4e63c91e0586.PNG)
![IMG_0044](https://user-images.githubusercontent.com/52463/56815871-a06ae100-6842-11e9-9876-09f09ea0f8c6.PNG)

**Comment by v4lli** [comment]
Good point, we should show a loading screen until at least the webapp has loaded completely (to avoid situations like in your first screenshot).

Having a loading indicator/screen for the second screenshot case is a little harder (it's not easy to get tile-loading-progress-information out of openlayers).

The drawer handle for the forecast stuff should be hidden by default, I guess. Only views which need it can enable it from javascript. cc @Nina2244

**Comment by v4lli** [comment]
Implemented on Android, created issue in meteocool/ios for iOS integration.
