### ISSUE TITLE
on-boarding: Ask for location immediately

### ISSUE THREAD

**Issue by pew** [v4lli/meteocool#148]
Right now you need to go through the on-boarding process when installing meteocool and enable location services by clicking a button. This requires reading the on-boarding screens but most people don't do it.

one idea: just ask for location / notification permissions right in the beginning for after onboarding (maybe except someone says **no** explicitly - maybe even with a second confirmation.. the app really doesn't make any sense without it?)

**Comment by v4lli** [comment]
@pew please try the latest iOS master branch in the simulator and try the following with a newly installed app:

- "later" everything in onboarding
- press the locate-me button (choosing always additionally prompts for notifications)

- (re-install app and re-"later" everythin in onboarding)
- force quit app + launch again

**Comment by Wayneoween** [comment]
Nice. Me like!
