### ISSUE TITLE
Show version number

### ISSUE THREAD

**Issue by Wayneoween** [v4lli/meteocool#149]
As far as I can see, neither in the iOS App-Store nor in the App itself there is any version indicator.

This may be helpful, should there be confusion about which version a user that creates a bug report actually uses.
In Testflight the version is visible.

My idea is in the App-Description display the latest changelog entry or something like that. In the App either in "about" or behind the "i" in the lower right corner. Scrollable row, version number "hidden" to the right?

**Comment by v4lli** [comment]
Done in 2.0, Testflight release coming soon
