### ISSUE TITLE
Show tooltips for custom controls

### ISSUE THREAD

**Issue by chrismayer** [v4lli/meteocool#155]
In order to improve usability it would be nice to have tooltips for the custom controls in the upper-right corner of the map (as it is done for the other controls like zoomin / zoomout)

![grafik](https://user-images.githubusercontent.com/1185547/58084972-236e2580-7bbc-11e9-91f8-a563de942e09.png)

So the user can get a quick idea what the tools do before they have to be activated (at least on mouse-based systems).

**Comment by v4lli** [comment]
Good point! Fixed.

**Comment by chrismayer** [comment]
Cool, thanks!

**Comment by v4lli** [comment]
I've discovered a few issues with the interface refactoring which includes the fix for this issue, so deployment to meteocool.com will take a few more days, just FYI.
