### ISSUE TITLE
no location with microG

### ISSUE THREAD

**Issue by obifur** [v4lli/meteocool#194]
Device: Galaxy A3
OS: Android 8.0 with microG
microG: 0.2.10.19420
meteocool v 1.5.5

Issue: 
(Remark: Location Accuracy is turned on and I always have the correct position via Wifi/mobile networks)
1. indoor (no GPS):
When pushing the locate me button, I get the error "schlechtes GPS-Signal" (bad GPS signal) and nothing happens. Other apps show my correct position.
2. outdoor (good GPS signal)
When pushing the locate me button, nothing happens. Other apps show my correct position.

probably this behavior is related to microG..?

**Comment by Wheedman** [comment]
I am currently working on a redesign according kind of this issues. I cannot say that this is related to a specific device but I do know that there can occur some problems about the location settings and the attachment to the javascript interface. 
I hope my update will fix your issue aswell. 
Please be patient and stay tuned!

**Comment by Wheedman** [comment]
@obifur I also tried it on my other device (Sony Xperia Z3 compact) with LineageOS without Google Services. Is it possible that you also have a custom android without Google Services? 
Between meteocool version 1.1 and 1.5 i changed the location service from the manual one to the google location service. So this could also be your problem.

**Comment by obifur** [comment]
well, as I wrote, I use a stock rom but removed original google service and replaced it by [microG](https://microg.org/). It contains a "Service Core (GmsCore)" and a "Unified Network Location Provider (UnifiedNlp)". This should have the same functionality and apps shouldn't notice it.. I think.. However I'm not an expert on this but all other apps I use do work.

**Comment by obifur** [comment]
I don't run this setup anymore, so I can't reproduce it. Also another guy with this setup seemed to have the same problem with other apps like "clevertanken" and found a solution by downgrade microg to 0.2.6.. 
So probably this issue was not related to you app and I will close it :)
