### ISSUE TITLE
Radar map gets cut off when starting preview

### ISSUE THREAD

**Issue by torantal** [v4lli/meteocool#198]
In this example the map starts with a clearly visible weather front in the south, which gets cut off when starting the preview.

https://youtu.be/xGzI1VaU8oM

![20200817_071343](https://user-images.githubusercontent.com/6267029/90359608-abf6a280-e059-11ea-8194-f435d1a93ab0.jpg)

**Comment by v4lli** [comment]
Fixed. The forecast now spans the whole radar coverage area. Updates for both iOS and Android apps coming soon :)
