### ISSUE TITLE
legende einbinden

### ISSUE THREAD

**Issue by v4lli** [v4lli/meteocool#25]

**Comment by v4lli** [comment]
The legend needs to be auto-generated from the dbz2color() function in dwd2geojson.py.

**Comment by pew** [comment]
I put this in dwd since it only needs to be updated when they update something (I guess?), also requires someone with basic math skills to fix the actual size.

**Comment by v4lli** [comment]
part #1 has been integrated, leaving this as unresolved until the legend gets numeric dbZ values every 20 pixel or so. the values should be between 0 (leftmost) and 96 (rightmost).

**Comment by v4lli** [comment]
As discussed, we don't want a numeric scale because no one really knows what the numbers mean. A human-readable range from "light mist" to "thunderstorm" would be better. @pew

**Comment by v4lli** [comment]
numeric scale done, closing this until someone has a better idea for simpler visualisation.
