### ISSUE TITLE
Screenshots for "About" and README.md

### ISSUE THREAD

**Issue by v4lli** [v4lli/meteocool#75]
We need some nice lookin screenshots for both the "About" page (regarding the iOS PWA and how much better it looks than the normal safari site) and the github README (iOS + Desktop).

All screenshots should contain all our features (i.e. a nice, big storm AND some accumulated lightning strikes).

**Comment by pew** [comment]
I think we can close this, there are screenshots on the about page, readme and app stores now?

**Comment by v4lli** [comment]
done

<img width="1176" alt="Screenshot 2019-05-11 13 33 19" src="https://user-images.githubusercontent.com/1577223/57573080-444bb380-7423-11e9-935d-2a990f5026f6.png">
