### ISSUE TITLE
modal doesn't conform to dark mode

### ISSUE THREAD

**Issue by v4lli** [v4lli/meteocool#84]
The "About" modal should also change to a white-on-black kind of style. It's way to bright otherwise.

**Comment by pew** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by pew** [comment]
someone please check 1a71b3c - I don't like how the modal close buttons look but AFAIK non others are provided by bootstrap. I guess one could adapt the css styles directly but ...
