### ISSUE TITLE
GUI elements hidden by iPhone X notch

### ISSUE THREAD

**Issue by v4lli** [v4lli/meteocool#85]
Some GUI elements (zoom controls) are hidden behind the speaker notch in iPhone X widescreen.

**Comment by pew** [comment]
does [this](https://css-tricks.com/the-notch-and-css/) also affect the mobile iOS app?

**Comment by v4lli** [comment]
I think we already set those tags. Widescreen is currently disabled on the iOS app, and the on the web app, the buttons are partly hidden by the notch. ~_~

**Comment by pew** [comment]
`viewport-fit=contain` would be a *fix*, but I don't like it. Any votes?

<img width="1048" alt="Screen Shot 2019-05-12 at 6 28 09 PM" src="https://user-images.githubusercontent.com/52463/57585100-b552a000-74e3-11e9-8e20-0155f87c0d3a.png">

**Comment by pew** [comment]
what about:

<img width="1048" alt="Screen Shot 2019-05-12 at 6 42 18 PM" src="https://user-images.githubusercontent.com/52463/57585239-af5dbe80-74e5-11e9-889c-053254859cdf.png">

**Comment by v4lli** [comment]
I think those changes would also affect the apps; how about simply moving the controls in by xx pixels on both sides if iOS safari is in widescreen? We could do that in JS, we have callbacks for rotation anyway.

**Comment by pew** [comment]
heard the word callback, I'm out 🏃

**Comment by v4lli** [comment]
Fixed in meteocool/web
