### ISSUE TITLE
switch to OSM vector tiles

### ISSUE THREAD

**Issue by pew** [v4lli/meteocool#94]
right now, switch to this one: https://openmaptiles.com/downloads/tileset/osm/

at some point we need to build them ourselves: https://planet.openstreetmap.org

**Comment by v4lli** [comment]
This was from when we had the original OSM tiles. Switched to pre-rendered CARTO tiles for the baselayer a while ago and everybody wants a native maps anyways. Also don't have 50GB free disk space. 😅
